/**
 * Custom Report Metadata API (US-14.7)
 *
 * GET /api/reports/custom/metadata
 *
 * Returns available columns and filter options for each data source
 */

export default defineEventHandler(async (event) => {
  const session = await getUserSession(event)

  if (!session?.user) {
    throw createError({
      statusCode: 401,
      statusMessage: 'Unauthorized',
    })
  }

  return {
    dataSources: [
      {
        id: 'assets',
        label: 'Assets',
        description: 'Fleet assets including vehicles and equipment',
        icon: 'i-lucide-truck',
      },
      {
        id: 'work_orders',
        label: 'Work Orders',
        description: 'Maintenance and repair work orders',
        icon: 'i-lucide-wrench',
      },
      {
        id: 'maintenance_schedules',
        label: 'Maintenance Schedules',
        description: 'Scheduled maintenance plans',
        icon: 'i-lucide-calendar',
      },
      {
        id: 'fuel_transactions',
        label: 'Fuel Transactions',
        description: 'Fuel entries and consumption data',
        icon: 'i-lucide-fuel',
      },
      {
        id: 'inspections',
        label: 'Inspections',
        description: 'Pre-start and other inspections',
        icon: 'i-lucide-clipboard-check',
      },
    ],
    columns: {
      assets: [
        { field: 'id', label: 'ID', type: 'uuid', filterable: false, sortable: true },
        {
          field: 'assetNumber',
          label: 'Asset Number',
          type: 'string',
          filterable: true,
          sortable: true,
        },
        { field: 'make', label: 'Make', type: 'string', filterable: true, sortable: true },
        { field: 'model', label: 'Model', type: 'string', filterable: true, sortable: true },
        { field: 'year', label: 'Year', type: 'number', filterable: true, sortable: true },
        {
          field: 'licensePlate',
          label: 'License Plate',
          type: 'string',
          filterable: true,
          sortable: true,
        },
        { field: 'vin', label: 'VIN', type: 'string', filterable: true, sortable: true },
        {
          field: 'status',
          label: 'Status',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['active', 'inactive', 'maintenance', 'disposed'],
        },
        {
          field: 'mileage',
          label: 'Mileage (km)',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'operationalHours',
          label: 'Operational Hours',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'categoryId',
          label: 'Category ID',
          type: 'uuid',
          filterable: true,
          sortable: false,
        },
        { field: 'createdAt', label: 'Created At', type: 'date', filterable: true, sortable: true },
        { field: 'updatedAt', label: 'Updated At', type: 'date', filterable: true, sortable: true },
      ],
      work_orders: [
        { field: 'id', label: 'ID', type: 'uuid', filterable: false, sortable: true },
        {
          field: 'workOrderNumber',
          label: 'WO Number',
          type: 'string',
          filterable: true,
          sortable: true,
        },
        { field: 'title', label: 'Title', type: 'string', filterable: true, sortable: true },
        {
          field: 'status',
          label: 'Status',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: [
            'draft',
            'pending_approval',
            'open',
            'in_progress',
            'pending_parts',
            'completed',
            'closed',
          ],
        },
        {
          field: 'priority',
          label: 'Priority',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['low', 'medium', 'high', 'critical'],
        },
        { field: 'assetId', label: 'Asset ID', type: 'uuid', filterable: true, sortable: false },
        {
          field: 'assignedToId',
          label: 'Assigned To ID',
          type: 'uuid',
          filterable: true,
          sortable: false,
        },
        { field: 'dueDate', label: 'Due Date', type: 'date', filterable: true, sortable: true },
        {
          field: 'completedAt',
          label: 'Completed At',
          type: 'date',
          filterable: true,
          sortable: true,
        },
        {
          field: 'laborCost',
          label: 'Labor Cost',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'partsCost',
          label: 'Parts Cost',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'totalCost',
          label: 'Total Cost',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'estimatedDuration',
          label: 'Estimated Duration (min)',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'actualDuration',
          label: 'Actual Duration (min)',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        { field: 'createdAt', label: 'Created At', type: 'date', filterable: true, sortable: true },
        { field: 'updatedAt', label: 'Updated At', type: 'date', filterable: true, sortable: true },
      ],
      maintenance_schedules: [
        { field: 'id', label: 'ID', type: 'uuid', filterable: false, sortable: true },
        { field: 'name', label: 'Name', type: 'string', filterable: true, sortable: true },
        {
          field: 'scheduleType',
          label: 'Schedule Type',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['time_based', 'usage_based', 'combined'],
        },
        { field: 'assetId', label: 'Asset ID', type: 'uuid', filterable: true, sortable: false },
        {
          field: 'categoryId',
          label: 'Category ID',
          type: 'uuid',
          filterable: true,
          sortable: false,
        },
        {
          field: 'intervalType',
          label: 'Interval Type',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['daily', 'weekly', 'monthly', 'quarterly', 'annually', 'custom'],
        },
        {
          field: 'intervalValue',
          label: 'Interval Value',
          type: 'number',
          filterable: true,
          sortable: true,
        },
        {
          field: 'intervalMileage',
          label: 'Interval Mileage',
          type: 'number',
          filterable: true,
          sortable: true,
        },
        {
          field: 'intervalHours',
          label: 'Interval Hours',
          type: 'number',
          filterable: true,
          sortable: true,
        },
        {
          field: 'nextDueDate',
          label: 'Next Due Date',
          type: 'date',
          filterable: true,
          sortable: true,
        },
        {
          field: 'lastGeneratedAt',
          label: 'Last Generated At',
          type: 'date',
          filterable: true,
          sortable: true,
        },
        {
          field: 'isActive',
          label: 'Is Active',
          type: 'boolean',
          filterable: true,
          sortable: true,
        },
        { field: 'createdAt', label: 'Created At', type: 'date', filterable: true, sortable: true },
        { field: 'updatedAt', label: 'Updated At', type: 'date', filterable: true, sortable: true },
      ],
      fuel_transactions: [
        { field: 'id', label: 'ID', type: 'uuid', filterable: false, sortable: true },
        { field: 'assetId', label: 'Asset ID', type: 'uuid', filterable: true, sortable: false },
        {
          field: 'quantity',
          label: 'Quantity (L)',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'unitCost',
          label: 'Unit Cost',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'totalCost',
          label: 'Total Cost',
          type: 'number',
          filterable: true,
          sortable: true,
          aggregatable: true,
        },
        {
          field: 'fuelType',
          label: 'Fuel Type',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['diesel', 'petrol', 'electric', 'lpg', 'other'],
        },
        { field: 'odometer', label: 'Odometer', type: 'number', filterable: true, sortable: true },
        {
          field: 'engineHours',
          label: 'Engine Hours',
          type: 'number',
          filterable: true,
          sortable: true,
        },
        { field: 'vendor', label: 'Vendor', type: 'string', filterable: true, sortable: true },
        {
          field: 'transactionDate',
          label: 'Transaction Date',
          type: 'date',
          filterable: true,
          sortable: true,
        },
        {
          field: 'hasDiscrepancy',
          label: 'Has Discrepancy',
          type: 'boolean',
          filterable: true,
          sortable: true,
        },
        {
          field: 'source',
          label: 'Source',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['manual', 'authorization', 'external_sync'],
        },
        { field: 'createdAt', label: 'Created At', type: 'date', filterable: true, sortable: true },
        { field: 'updatedAt', label: 'Updated At', type: 'date', filterable: true, sortable: true },
      ],
      inspections: [
        { field: 'id', label: 'ID', type: 'uuid', filterable: false, sortable: true },
        { field: 'assetId', label: 'Asset ID', type: 'uuid', filterable: true, sortable: false },
        {
          field: 'templateId',
          label: 'Template ID',
          type: 'uuid',
          filterable: true,
          sortable: false,
        },
        {
          field: 'operatorId',
          label: 'Operator ID',
          type: 'uuid',
          filterable: true,
          sortable: false,
        },
        {
          field: 'status',
          label: 'Status',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['in_progress', 'completed', 'cancelled'],
        },
        {
          field: 'initiationMethod',
          label: 'Initiation Method',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['nfc', 'qr_code', 'manual'],
        },
        {
          field: 'overallResult',
          label: 'Overall Result',
          type: 'string',
          filterable: true,
          sortable: true,
        },
        { field: 'startedAt', label: 'Started At', type: 'date', filterable: true, sortable: true },
        {
          field: 'completedAt',
          label: 'Completed At',
          type: 'date',
          filterable: true,
          sortable: true,
        },
        {
          field: 'syncStatus',
          label: 'Sync Status',
          type: 'enum',
          filterable: true,
          sortable: true,
          options: ['synced', 'pending', 'failed'],
        },
        { field: 'createdAt', label: 'Created At', type: 'date', filterable: true, sortable: true },
        { field: 'updatedAt', label: 'Updated At', type: 'date', filterable: true, sortable: true },
      ],
    },
    filterOperators: {
      string: [
        { value: 'eq', label: 'equals' },
        { value: 'neq', label: 'not equals' },
        { value: 'like', label: 'contains' },
        { value: 'isNull', label: 'is empty' },
        { value: 'isNotNull', label: 'is not empty' },
      ],
      number: [
        { value: 'eq', label: 'equals' },
        { value: 'neq', label: 'not equals' },
        { value: 'gt', label: 'greater than' },
        { value: 'gte', label: 'greater than or equal' },
        { value: 'lt', label: 'less than' },
        { value: 'lte', label: 'less than or equal' },
        { value: 'isNull', label: 'is empty' },
        { value: 'isNotNull', label: 'is not empty' },
      ],
      enum: [
        { value: 'eq', label: 'equals' },
        { value: 'neq', label: 'not equals' },
        { value: 'in', label: 'is one of' },
        { value: 'notIn', label: 'is not one of' },
      ],
      date: [
        { value: 'eq', label: 'equals' },
        { value: 'gt', label: 'after' },
        { value: 'gte', label: 'on or after' },
        { value: 'lt', label: 'before' },
        { value: 'lte', label: 'on or before' },
        { value: 'isNull', label: 'is empty' },
        { value: 'isNotNull', label: 'is not empty' },
      ],
      boolean: [{ value: 'eq', label: 'equals' }],
      uuid: [
        { value: 'eq', label: 'equals' },
        { value: 'neq', label: 'not equals' },
        { value: 'isNull', label: 'is empty' },
        { value: 'isNotNull', label: 'is not empty' },
      ],
    },
    aggregationTypes: [
      { value: 'count', label: 'Count' },
      { value: 'sum', label: 'Sum' },
      { value: 'avg', label: 'Average' },
      { value: 'min', label: 'Minimum' },
      { value: 'max', label: 'Maximum' },
    ],
  }
})
